name: Daily NBA Schedule

on:
  schedule:
    # Runs at 12:05 PM EST (16:05 UTC) every day
    - cron: '15 16 * * *'
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  post-schedule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Post NBA Schedule to Slack
        env:
          NBA_API_KEY: ${{ secrets.NBA_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          NBA_ALERTS_API_KEY: ${{ secrets.NBA_ALERTS_API_KEY }}
          NBA_STANDINGS_KEY: ${{ secrets.NBA_STANDINGS_KEY }}
          QUERY_TOOL_API_KEY: ${{ secrets.QUERY_TOOL_API_KEY }}
          STATS_API_KEY: ${{ secrets.STATS_API_KEY }}
          ED_TEST_WEBHOOK_URL: ${{ secrets.ED_TEST_WEBHOOK_URL }}


        run: python main.py